from pathlib import Path
from shutil import copyfile

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from app.core.enums import CaseStatus
from app.db.base import Base
from app.services.cases import get_case, start_review
from conftest import TIME
from sqlalchemy import MetaData, create_engine, inspect, select
from sqlalchemy.orm import Session

ROOT = Path(__file__).resolve().parents[1]


def test_initial_migration_upgrade_matches_models_and_downgrades() -> None:
    config = Config(str(ROOT / "alembic.ini"))
    with create_engine("sqlite://").begin() as connection:
        config.attributes["connection"] = connection
        command.upgrade(config, "head")
        assert set(inspect(connection).get_table_names()) == set(Base.metadata.tables) | {
            "alembic_version"
        }
        assert compare_metadata(MigrationContext.configure(connection), Base.metadata) == []
        command.downgrade(config, "base")
        assert inspect(connection).get_table_names() == ["alembic_version"]


def test_autogenerated_migration_is_self_contained_and_executable(tmp_path: Path) -> None:
    # Exercise the documented command with UTC/JSON custom types on an empty schema.
    copyfile(ROOT / "alembic" / "env.py", tmp_path / "env.py")
    copyfile(ROOT / "alembic" / "script.py.mako", tmp_path / "script.py.mako")
    (tmp_path / "versions").mkdir()
    config = Config()
    config.set_main_option("script_location", str(tmp_path))
    with create_engine("sqlite://").begin() as connection:
        config.attributes["connection"] = connection
        revision = command.revision(config, message="round trip", autogenerate=True)
        source = Path(revision.path).read_text(encoding="utf-8")
        assert "app.db.base" not in source
        command.upgrade(config, "head")
        assert compare_metadata(MigrationContext.configure(connection), Base.metadata) == []


def test_upgrade_preserves_legacy_explanations_decisions_and_open_cases() -> None:
    config = Config(str(ROOT / "alembic.ini"))
    with create_engine("sqlite://").begin() as connection:
        config.attributes["connection"] = connection
        command.upgrade(config, "0001_initial")
        old = MetaData()
        old.reflect(connection)
        connection.execute(
            old.tables["drivers"].insert(),
            {
                "id": 1,
                "external_driver_id": "LEGACY",
                "name": "Legacy driver",
                "status": "active",
                "created_at": TIME,
                "updated_at": TIME,
            },
        )
        for case_id, status in ((1, "awaiting_driver_explanation"), (2, "dismissed")):
            connection.execute(
                old.tables["fraud_cases"].insert(),
                {
                    "id": case_id,
                    "driver_id": 1,
                    "fraud_type": "gps_spoofing",
                    "fraud_types": ["gps_spoofing"],
                    "risk_score": 30,
                    "score_breakdown": {"gps_spoofing": 30},
                    "rule_config": {"version": "old"},
                    "detection_fingerprint": str(case_id) * 64,
                    "status": status,
                    "created_at": TIME,
                    "updated_at": TIME,
                },
            )
        connection.execute(
            old.tables["driver_explanations"].insert(),
            {
                "id": 1,
                "case_id": 2,
                "explanation": "Historical response",
                "attachment_metadata": [],
                "created_at": TIME,
            },
        )
        connection.execute(
            old.tables["case_decisions"].insert(),
            {
                "id": 1,
                "case_id": 2,
                "decision": "dismissed",
                "reviewer": "legacy-reviewer",
                "reason": "Historical decision",
                "created_at": TIME,
            },
        )
        retained = ["drivers", "fraud_cases", "driver_explanations", "case_decisions"]
        snapshots = {name: connection.execute(select(old.tables[name])).all() for name in retained}
        command.upgrade(config, "head")
        for name, rows in snapshots.items():
            assert connection.execute(select(old.tables[name])).all() == rows
        with Session(connection) as session:
            historical = get_case(session, 2)
            assert historical.alert_id is None
            assert historical.explanations[0].explanation == "Historical response"
            assert historical.decisions[0].actor_type == "human"
            resumed = start_review(session, 1, "internal-reviewer", "Resume migrated case")
            assert resumed.status == CaseStatus.UNDER_REVIEW
