from pathlib import Path
from shutil import copyfile

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from app.db.base import Base
from sqlalchemy import create_engine, inspect

ROOT = Path(__file__).resolve().parents[1]


def test_initial_migration_upgrade_matches_models_and_downgrades() -> None:
    config = Config(str(ROOT / "alembic.ini"))
    with create_engine("sqlite://").begin() as connection:
        config.attributes["connection"] = connection
        command.upgrade(config, "head")
        assert set(inspect(connection).get_table_names()) == set(Base.metadata.tables) | {
            "alembic_version"
        }
        assert compare_metadata(MigrationContext.configure(connection), Base.metadata) == []
        command.downgrade(config, "base")
        assert inspect(connection).get_table_names() == ["alembic_version"]


def test_autogenerated_migration_is_self_contained_and_executable(tmp_path: Path) -> None:
    # Exercise the documented command with UTC/JSON custom types on an empty schema.
    copyfile(ROOT / "alembic" / "env.py", tmp_path / "env.py")
    copyfile(ROOT / "alembic" / "script.py.mako", tmp_path / "script.py.mako")
    (tmp_path / "versions").mkdir()
    config = Config()
    config.set_main_option("script_location", str(tmp_path))
    with create_engine("sqlite://").begin() as connection:
        config.attributes["connection"] = connection
        revision = command.revision(config, message="round trip", autogenerate=True)
        source = Path(revision.path).read_text(encoding="utf-8")
        assert "app.db.base" not in source
        command.upgrade(config, "head")
        assert compare_metadata(MigrationContext.configure(connection), Base.metadata) == []
