Tôi tổng hợp được **20 phương pháp và thành phần hỗ trợ chống gian lận**, gồm paper học thuật và các hệ thống do Grab, Uber, GSM công bố.

Tôi truy xuất được phần tóm tắt bảng “Tổng hợp gian lận hãng xe”, nhưng chưa lấy lại được nguyên văn toàn bộ 32 dòng. Vì vậy, phần đối chiếu dưới đây sử dụng các nhóm hành vi đã tìm lại được: **cuốc ảo, GPS giả, can thiệp “Mắt thần”, giấu chuyến, gian lận quãng đường/phí, tài khoản giả hoặc thuê mượn, thông đồng và thao túng giá**.

Quy ước mức bằng chứng:

* **NC:** Có nghiên cứu/thử nghiệm; chưa đủ bằng chứng triển khai vận hành.
* **TK:** Có nguồn từ doanh nghiệp mô tả đã áp dụng, theo phạm vi được ghi.
* **HT:** Thành phần hỗ trợ kiểm tra hoặc điều tra; cần kết hợp với phương pháp khác.

Cột “phù hợp” và phần ưu, nhược điểm bao gồm **đánh giá kỹ thuật của tôi dựa trên nguồn**. Việc chuyển một phương pháp sang loại gian lận khác cần được kiểm chứng trên dữ liệu tương ứng.

Bảng phương pháp dưới đây dùng mã **M01–M20** để nối với ma trận công nghệ phía sau.

| Mã      | Phương pháp và nguồn                                                                                                                                                                                                                                   | Mức bằng chứng                                                          | Công nghệ, nguyên lý                                                                                                                                  | Ưu điểm                                                                                                   | Nhược điểm / giới hạn                                                                                                   | Phù hợp chống loại gian lận nào                                                                              |
| ------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ |
| **M01** | **Rule engine — luật nghiệp vụ.** [Griffin, Grab, 2019](https://engineering.grab.com/griffin)                                                                                                                                                          | **TK — Grab**, nhiều mảng dịch vụ                                       | Đánh giá điều kiện trên tài khoản, thanh toán, lịch sử giao dịch; kết hợp thành quyết định chấp nhận, từ chối hoặc yêu cầu kiểm tra thêm.             | Dễ giải thích, triển khai nhanh, xử lý tốt hành vi đã biết.                                               | Phải duy trì luật; dễ bỏ sót thủ đoạn mới; nhiều luật có thể xung đột hoặc gây báo nhầm.                                | Lạm dụng khuyến mãi, giao dịch không hợp lệ; có thể xây luật cho hủy chuyến, phụ phí, điều kiện nhận thưởng. |
| **M02** | **Velocity checks — đếm hành vi trong cửa sổ thời gian.** [Grab Trust Counter, 2019](https://engineering.grab.com/using-grabs-trust-counter-service-to-detect-fraud-successfully)                                                                      | **TK — Grab**                                                           | Đếm số lần một cặp tài xế–khách giao dịch trong khoảng thời gian; đưa kết quả vào rule engine.                                                        | Nhẹ, phản ứng nhanh, bằng chứng dễ trình bày: tần suất, đối tượng, thời điểm.                             | Khách quen hoặc tuyến cố định có thể giống thông đồng; đối tượng phân tán giao dịch có thể tránh ngưỡng.                | Tự đặt cuốc, cuốc ảo lặp lại, cày thưởng, thông đồng tài xế–khách.                                           |
| **M03** | **SFDS — Speed-based Fraud Detection System.** Liu, Ni, Krishnan, *IEEE TVT*, 2014: [Fraud Detection From Taxis’ Driving Behaviors](https://researchportal.hkust.edu.hk/en/publications/fraud-detection-from-taxis-driving-behaviors/)                 | **NC — dữ liệu taxi thực**                                              | Mô hình hóa thông tin tốc độ để tìm dấu hiệu chỉnh hệ số đồng hồ tính cước; khai thác quan hệ giữa việc tăng quãng đường báo cáo và tốc độ báo cáo.   | Ít phụ thuộc bản đồ; được thiết kế để giảm ảnh hưởng của sai số vị trí.                                   | Nhắm vào một cơ chế gian lận đồng hồ cụ thể; khả năng chuyển sang ứng dụng tính cước hiện đại cần kiểm thử.             | Can thiệp đồng hồ, khai tăng quãng đường tính tiền.                                                          |
| **M04** | **iBAT — Isolation-Based Anomalous Trajectory.** Zhang và cộng sự, UbiComp 2011: [paper gốc](https://cs.nju.edu.cn/_upload/tpl/01/0b/267/template267/zhouzh.files/publication/ubicomp11.pdf)                                                           | **NC — dữ liệu taxi thực**                                              | Chuyển hành trình thành chuỗi ô không gian; tìm các tuyến ít gặp và khác biệt trong nhóm cùng điểm đầu–cuối bằng cơ chế isolation.                    | Không cần nhãn gian lận; phù hợp làm mô hình đối chứng ban đầu.                                           | Cần lịch sử tuyến đủ phong phú; đường mới, cấm đường hoặc yêu cầu của khách có thể bị coi là bất thường.                | Đi đường vòng, hành trình bất thường cần hậu kiểm.                                                           |
| **M05** | **iBOAT — Isolation-Based Online Anomalous Trajectory Detection.** Chen và cộng sự, *IEEE TITS*, 2013: [nguồn xuất bản](https://ieeexplore.ieee.org/document/6450098/)                                                                                 | **NC — dữ liệu taxi thực**                                              | So sánh hành trình đang diễn ra với các tuyến bình thường trong lịch sử, có xét yếu tố thời gian.                                                     | Có thể cảnh báo trước khi chuyến kết thúc; phù hợp theo dõi hành trình trực tiếp.                         | Phụ thuộc chất lượng GPS và dữ liệu tham chiếu; cần phân biệt đường vòng hợp lệ với cố ý kéo dài cuốc.                  | Đi vòng, lệch tuyến, kéo dài hành trình.                                                                     |
| **M06** | **Phân loại đường vòng bằng logistic regression.** Tian và cộng sự, bản 2020: [How to Eliminate Detour Behaviors in E-hailing?](https://arxiv.org/html/1910.06949v3)                                                                                   | **NC — preprint, dữ liệu taxi thực**                                    | Dùng tỷ lệ dư quãng đường và dư thời gian so với tuyến kế hoạch làm đầu vào cho logistic regression; mở rộng sang phát hiện trực tuyến.               | Mô hình nhỏ, dễ giải thích; xét cả thời gian và khoảng cách.                                              | Cần nhãn và ước lượng thời gian đi hợp lý; ETA sai hoặc giao thông bất thường làm giảm độ tin cậy.                      | Đi vòng để tăng cước, hành trình kéo dài bất hợp lý.                                                         |
| **M07** | **RL4OASD — phát hiện đoạn hành trình bất thường bằng deep reinforcement learning.** Zhang và cộng sự, 2022: [paper](https://arxiv.org/abs/2211.08415)                                                                                                 | **NC — thử nghiệm trên hai bộ dữ liệu thực**                            | Hai mạng học biểu diễn và phát hiện đoạn bất thường; sử dụng LSTM và học tăng cường. Không cần nhãn thật để huấn luyện, nhưng có bước tạo nhãn nhiễu. | Khoanh vùng được đoạn bất thường; giảm nhu cầu gán nhãn thủ công.                                         | Huấn luyện và giải thích phức tạp; phụ thuộc cách tạo nhãn nhiễu và thiết kế phần thưởng.                               | Các đoạn đi vòng hoặc lệch tuyến tinh vi bên trong một chuyến.                                               |
| **M08** | **DeepPOSE — phát hiện giả mạo GPS bằng cảm biến chuyển động.** Jiang, Wu, Xin, 2022: [paper và tóm tắt của tác giả](https://digitalcommons.odu.edu/ece_fac_pubs/302/)                                                                                 | **NC — nền tảng di động; chưa xác nhận triển khai tại hãng taxi**       | CNN và RNN khôi phục quỹ đạo từ cảm biến chuyển động, kết hợp bản đồ rồi kiểm tra sự phù hợp với GPS.                                                 | Có tín hiệu kiểm chứng bổ sung cho tọa độ GPS; hướng nghiên cứu sát bài toán cuốc giả.                    | Cần thu cảm biến; chịu nhiễu và sai lệch tích lũy; khó bảo đảm khi nhiều nguồn dữ liệu cùng bị can thiệp.               | GPS giả, mô phỏng chuyển động để tạo cuốc ảo.                                                                |
| **M09** | **Device intelligence và đối chiếu nhiều tín hiệu vị trí.** [GrabDefence, 2024](https://www.grab.com/inside-grab/stories/grabdefence-anti-fraud-technology-for-southeast-asias-digital-age/)                                                           | **TK — Grab/GrabDefence**                                               | Nhận diện thiết bị, phát hiện dấu hiệu sửa đổi; so sánh telemetry, cảm biến, trạm di động và lịch sử hành vi để tìm bất thường vị trí.                | Bao phủ cả môi trường thiết bị và hành vi; có thể kiểm tra ngay khi đăng nhập hoặc giao dịch.             | Chi tiết mô hình không được công bố đầy đủ; thay máy, máy dùng chung hoặc môi trường mạng khác thường có thể gây nhiễu. | GPS giả, ứng dụng bị sửa, tái sử dụng thiết bị để tạo nhiều tài khoản, lạm dụng khuyến mãi.                  |
| **M10** | **RGCN — mạng nơ-ron đồ thị đa quan hệ.** [Paper nền tảng](https://arxiv.org/abs/1703.06103); [ứng dụng Grab, 2022](https://engineering.grab.com/graph-for-fraud-detection); [nghiên cứu Uber, 2021](https://www.uber.com/us/en/blog/fraud-detection/) | **TK — Grab. NC — mô hình Uber được dẫn chưa dùng trong production**    | Biểu diễn tài khoản, thiết bị và các quan hệ thành đồ thị; tổng hợp thông tin từ những thực thể liên quan để chấm điểm rủi ro.                        | Phát hiện nhóm thông đồng mà từng tài khoản riêng lẻ có thể trông bình thường; tận dụng được ít nhãn.     | Xây dựng, cập nhật đồ thị tốn công; dùng chung IP hoặc thiết bị chưa đủ chứng minh gian lận.                            | Cuốc ảo có tổ chức, tài khoản liên kết, thông đồng tài xế–khách, lạm dụng thưởng theo nhóm.                  |
| **M11** | **GraphBEAN và bộ gán nhãn loại gian lận.** Fathony, Ng, Chen, IJCNN 2023: [Interaction-Focused Anomaly Detection… và triển khai Grab](https://engineering.grab.com/graph-anomaly-model)                                                               | **NC + TK — GrabFood/GrabMart**; áp dụng sang taxi là hướng chuyển giao | Graph autoencoder học tái tạo đồ thị hai phía; sai số tái tạo tạo điểm bất thường cho nút và giao dịch. Hệ thống bổ sung tagger dùng luật.            | Không cần nhãn khi học; chấm điểm cả đối tượng lẫn tương tác; hỗ trợ phát hiện mẫu mới.                   | Hành vi hiếm nhưng hợp lệ vẫn có thể bị báo; chưa có bằng chứng trong nguồn này về hiệu quả trên taxi.                  | Thông đồng hai phía, lạm dụng khuyến mãi; có thể nghiên cứu chuyển từ khách–cửa hàng sang khách–tài xế.      |
| **M12** | **SPADE — phát hiện cộng đồng đáng ngờ trên đồ thị biến đổi.** Jiang và cộng sự, PVLDB 2022: [paper](https://www.vldb.org/pvldb/vol16/p461-jiang.pdf)                                                                                                  | **NC — nghiên cứu NUS/Grab**, có đánh giá quy mô lớn                    | Duy trì và cập nhật các đồ thị con có mật độ liên kết đáng ngờ; dùng thuật toán đồ thị tăng dần.                                                      | Phù hợp dữ liệu quan hệ thay đổi liên tục; không bắt buộc huấn luyện mạng nơ-ron.                         | Cần định nghĩa hàm nghi ngờ phù hợp; nhóm gian lận liên kết thưa có thể khó phát hiện.                                  | Nhóm tài khoản thông đồng, mạng lưới giao dịch giả, cày thưởng có tổ chức.                                   |
| **M13** | **Risk Entity Watch + HAIFA.** [Uber, 2023](https://www.uber.com/us/en/blog/risk-entity-watch/)                                                                                                                                                        | **TK — Uber**                                                           | Phát hiện bất thường không giám sát ở cấp tài khoản, thiết bị, phương tiện thanh toán…; HAIFA dùng histogram để giải thích đặc trưng bất thường.      | Phát hiện hành vi chưa có nhãn; đưa ra lý do để chuyên viên kiểm tra.                                     | Bất thường không đồng nghĩa gian lận; cần chuẩn hóa theo thời gian và nhóm người dùng; phát sinh khối lượng rà soát.    | Tài khoản có lịch sử cuốc, thanh toán hoặc hoạt động bất thường; bổ sung cho các luật đã biết.               |
| **M14** | **RADAR — phát hiện đợt gian lận và đề xuất luật.** [Uber, 2022](https://www.uber.com/us/en/blog/project-radar-intelligent-early-fraud-detection/)                                                                                                     | **TK — thanh toán Uber**                                                | Orbit/KTR phân tích chuỗi thời gian; FP-Growth tìm mẫu; Spark xử lý dữ liệu; chuyên viên xem xét luật được đề xuất.                                   | Phát hiện các đợt tấn công mới; ưu tiên theo thiệt hại dự kiến; kết nối với quy trình điều tra.           | Thiên về bất thường tổng hợp; dữ liệu thanh toán có độ trễ; chưa phải mô hình xác định lỗi từng tài xế.                 | Gian lận thanh toán, chargeback, bùng phát giao dịch không thu được tiền.                                    |
| **M15** | **Face verification — xác minh người dùng tài khoản bằng khuôn mặt.** [Uber Real-Time ID Check, 2017](https://www.uber.com/us/en/blog/real-time-id-check/)                                                                                             | **TK — Uber**                                                           | Yêu cầu selfie, phát hiện khuôn mặt và so khớp với ảnh đã xác minh; nguồn mô tả Microsoft Face API.                                                   | Đánh trực tiếp vào việc người lái không trùng chủ tài khoản; có thể kiểm tra lại trong quá trình sử dụng. | Ảnh kém chất lượng hoặc thay đổi diện mạo gây sai lệch; một lần xác minh không bảo đảm danh tính trong toàn bộ ca.      | Thuê/mượn tài khoản, dùng tài khoản bị chiếm đoạt, thay người lái.                                           |
| **M16** | **PIN xác nhận trước khi bắt đầu cuốc.** [Uber Verify Your Ride](https://help.uber.com/riders/article/whats-verify-my-ride/?nodeId=2ddbb5e8-0dd3-4048-b9ee-f6b5e5311e25)                                                                               | **TK — tính năng Uber**                                                 | Khách nhận mã PIN cho chuyến; tài xế nhập mã để bắt đầu chuyến tương ứng.                                                                             | Đơn giản; tạo thêm dấu vết xác nhận giữa khách và tài xế.                                                 | PIN có thể được chia sẻ từ xa; không giải quyết được thông đồng hai phía.                                               | Bắt đầu cuốc khi chưa đón đúng khách, nhầm khách/xe; hỗ trợ hạn chế một số cuốc không được khách xác nhận.   |
| **M17** | **Phát hiện người ngồi trên xe bằng cảm biến — “Mắt thần”.** [Nguồn CAND về hệ thống trên xe GSM, 2026](https://cand.vn/bat-3-tai-xe-taxi-su-dung-thiet-bi-vo-hieu-hoa-mat-than-de-chiem-doat-tien-cua-cong-ty-post805016.html)                        | **TK — GSM**; nguồn mô tả hệ thống qua vụ điều tra                      | Cảm biến hồng ngoại nhận biết khách ở ghế phụ và hàng ghế sau. Việc ghép tín hiệu này với nhật ký cuốc là hướng đối soát phù hợp.                     | Có tín hiệu vật lý về sự hiện diện của khách; hữu ích khi chuyến không được ghi nhận trên ứng dụng.       | Đã có vụ việc can thiệp cảm biến; nguồn chưa công bố đầy đủ logic đối soát hay độ chính xác.                            | Giấu chuyến, chở khách ngoài hệ thống để giữ tiền cước.                                                      |
| **M18** | **Thiết kế cơ chế giảm động cơ thông đồng: thưởng và thời gian chờ tái kích hoạt.** Tripathy và cộng sự, *Decision Sciences*, 2023: [Driver collusion in ride-hailing platforms](https://onlinelibrary.wiley.com/doi/full/10.1111/deci.12561)          | **NC — mô hình phân tích kinh tế**                                      | Điều chỉnh cấu trúc thưởng hoặc đặt khoảng chờ sau khi tài xế tắt ứng dụng, nhằm giảm lợi ích của việc phối hợp giảm nguồn cung.                      | Tác động vào động cơ gian lận; không cần xác định từng cuốc giả.                                          | Kết quả phụ thuộc giả định mô hình; thưởng làm tăng chi phí, khoảng chờ có thể ảnh hưởng tài xế hợp lệ.                 | Phối hợp tắt/bật ứng dụng để tạo thiếu xe và đẩy surge price.                                                |
| **M19** | **A* bot — trợ lý điều tra dùng LLM + RAG.** [Grab Integrity Analytics, 2024](https://engineering.grab.com/transforming-the-analytics-landscape-with-RAG-powered-LLM)                                                                                  | **TK — hỗ trợ điều tra nội bộ Grab**                                    | SpellVault chọn truy vấn phù hợp; Data-Arks cung cấp API cho SQL/Python; LLM tổng hợp kết quả cho người điều tra.                                     | Giảm thao tác truy vấn thủ công; gom nhiều dữ kiện thành hồ sơ dễ đọc.                                    | Phụ thuộc dữ liệu và truy vấn; có thể diễn giải sai; cần kiểm tra các kết luận quan trọng với dữ liệu gốc.              | Hỗ trợ điều tra nhiều nhóm gian lận, tổng hợp quan hệ và lịch sử hoạt động.                                  |
| **M20** | **Vision LLM cho OCR và trích xuất thông tin giấy tờ.** [Grab, 2025](https://engineering.grab.com/custom-vision-llm-at-grab)                                                                                                                           | **HT — thành phần xử lý tài liệu/eKYC**                                 | Vision encoder, language model, OCR và trích xuất trường dữ liệu; Grab mô tả mô hình tùy chỉnh từ các thành phần Qwen.                                | Xử lý nhiều mẫu giấy tờ, ngôn ngữ; tạo dữ liệu có cấu trúc để đối chiếu.                                  | **Đọc đúng giấy tờ không chứng minh giấy tờ thật**; vẫn cần kiểm tra tính xác thực và đối chiếu hồ sơ.                  | Hỗ trợ kiểm tra danh tính, bằng lái, đăng ký xe và thông tin không khớp.                                     |

Ma trận sau thể hiện **công nghệ cốt lõi của phương pháp được mô tả**, không đại diện cho toàn bộ hệ thống của hãng:

* **✓:** Có. **✕:** Không thuộc thành phần cốt lõi đang xét. **?:** Nguồn chưa công bố đủ để xác định.
* **ML/TK:** Máy học cổ điển hoặc phương pháp thống kê; **DL:** học sâu, tính riêng.
* **Đồ thị:** Quan hệ tài khoản/thực thể; không tính riêng việc sử dụng bản đồ đường.
* **CV:** Thị giác máy tính/sinh trắc hình ảnh. **Cảm biến:** Ngoài GPS và camera.
* LLM thuộc DL, nên phương pháp dùng LLM được tích ở cả hai cột.

| Phương pháp                           | Luật nghiệp vụ | ML/TK |  DL | Đồ thị | GPS/quỹ đạo |  CV | Cảm biến | LLM | RAG |
| ------------------------------------- | :------------: | :---: | :-: | :----: | :---------: | :-: | :------: | :-: | :-: |
| **M01 — Griffin**                     |        ✓       |   ✕   |  ✕  |    ✕   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M02 — Trust Counter**               |        ✓       |   ✕   |  ✕  |    ✕   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M03 — SFDS**                        |        ✕       |   ✓   |  ✕  |    ✕   |      ✓      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M04 — iBAT**                        |        ✕       |   ✓   |  ✕  |    ✕   |      ✓      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M05 — iBOAT**                       |        ✕       |   ✓   |  ✕  |    ✕   |      ✓      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M06 — Bộ phân loại logistic**       |        ✕       |   ✓   |  ✕  |    ✕   |      ✓      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M07 — RL4OASD**                     |        ✕       |   ✕   |  ✓  |    ✕   |      ✓      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M08 — DeepPOSE**                    |        ✕       |   ✕   |  ✓  |    ✕   |      ✓      |  ✕  |     ✓    |  ✕  |  ✕  |
| **M09 — Device intelligence/vị trí**  |        ✕       |   ?   |  ?  |    ✕   |      ✓      |  ✕  |     ✓    |  ✕  |  ✕  |
| **M10 — RGCN**                        |        ✕       |   ✕   |  ✓  |    ✓   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M11 — GraphBEAN + tagger**          |        ✓       |   ✕   |  ✓  |    ✓   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M12 — SPADE**                       |        ✕       |   ✕   |  ✕  |    ✓   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M13 — Risk Entity Watch/HAIFA**     |        ✕       |   ✓   |  ✓  |    ✕   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M14 — RADAR**                       |        ✓       |   ✓   |  ✕  |    ✕   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M15 — Xác minh khuôn mặt**          |        ✕       |   ?   |  ?  |    ✕   |      ✕      |  ✓  |     ✕    |  ✕  |  ✕  |
| **M16 — PIN xác nhận cuốc**           |        ✓       |   ✕   |  ✕  |    ✕   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M17 — Cảm biến “Mắt thần”**         |        ?       |   ✕   |  ✕  |    ✕   |      ✕      |  ✕  |     ✓    |  ✕  |  ✕  |
| **M18 — Cơ chế thưởng/thời gian chờ** |        ✓       |   ✕   |  ✕  |    ✕   |      ✕      |  ✕  |     ✕    |  ✕  |  ✕  |
| **M19 — A* bot**                      |        ✕       |   ✕   |  ✓  |    ✕   |      ✕      |  ✕  |     ✕    |  ✓  |  ✓  |
| **M20 — Vision LLM xử lý giấy tờ**    |        ✕       |   ✕   |  ✓  |    ✕   |      ✕      |  ✓  |     ✕    |  ✓  |  ✕  |

Ở **M09**, Grab xác nhận sử dụng ML nhưng không công bố đủ kiến trúc để phân biệt ML cổ điển với DL. **M13** hỗ trợ nhiều thuật toán, từ mô hình cây đến mạng nơ-ron; không có nghĩa mọi lần chấm điểm đều chạy cả hai. **M15** xác nhận công nghệ so khớp khuôn mặt, nhưng bài Uber được dẫn không mô tả kiến trúc mạng cụ thể.

Đối chiếu với các nhóm trong bảng gian lận trước, tôi đề xuất cách ghép phương pháp như sau. Đây là **đánh giá áp dụng cho dự án**, không phải tuyên bố các hãng đã triển khai đúng tổ hợp này.

| Nhóm hành vi                                                | Phương pháp nên kết hợp                                      | Dữ liệu cần có                                                                         | Điểm cần phân biệt khi điều tra                                                                                       |
| ----------------------------------------------------------- | ------------------------------------------------------------ | -------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------- |
| **Tự đặt cuốc, cuốc ảo, cày thưởng**                        | **M02 + M10/M11 + M09**                                      | Cuốc, cặp tài xế–khách, thiết bị, thanh toán, thưởng, GPS                              | Tần suất cao hoặc dùng chung thiết bị chỉ là tín hiệu; cần kiểm tra chuyến thực sự có diễn ra không.                  |
| **GPS giả, mô phỏng hành trình, ứng dụng bị sửa**           | **M09**, nghiên cứu bổ sung **M08**                          | GPS, telemetry thiết bị, cảm biến chuyển động, tín hiệu mạng                           | Phải phân biệt can thiệp có chủ đích với mất sóng và sai số GPS.                                                      |
| **Giấu chuyến, chở khách ngoài hệ thống**                   | **M17 + M01** để đối soát                                    | Hiện diện khách, trạng thái xe, nhật ký mở/đóng cuốc, thanh toán                       | Có khách khi không có cuốc là dấu hiệu cần kiểm tra. Muốn phát hiện phá cảm biến cần thêm giám sát sức khỏe thiết bị. |
| **Đi vòng, kéo dài quãng đường/thời gian**                  | Bắt đầu với **M06 hoặc M05**; đánh giá nâng cao bằng **M07** | GPS, điểm đầu–cuối, tuyến kế hoạch, giao thông, thay đổi yêu cầu của khách             | Đường dài hơn có thể giúp tránh tắc đường; cần xét lợi ích thực tế và yêu cầu của khách.                              |
| **Can thiệp đồng hồ/tăng quãng đường tính cước**            | **M03 + đối soát tính cước**                                 | Báo cáo tốc độ, quãng đường, thời gian, số tiền, phiên bản biểu giá                    | Phân biệt gian lận với lỗi đo lường hoặc lỗi phần mềm tính tiền.                                                      |
| **Thuê/mượn tài khoản, người lái hoặc giấy tờ không khớp**  | **M15 + M20**, kết hợp kiểm tra hồ sơ                        | Selfie, ảnh đã xác minh, giấy tờ, tài khoản, xe đăng ký                                | OCR chỉ trích xuất thông tin; việc xác thực danh tính và giấy tờ là bước riêng.                                       |
| **Thông đồng giảm nguồn cung để đẩy giá**                   | **M18** là hướng nghiên cứu trực tiếp                        | Trạng thái online/offline theo thời gian và khu vực, nhu cầu đặt xe, giá, phân bổ cuốc | Tắt ứng dụng đồng thời chưa đủ chứng minh thông đồng; có thể do sự cố hoặc điều kiện làm việc chung.                  |
| **Gian lận hủy chuyến, phụ phí hoặc tranh chấp thanh toán** | **M01 + M13 + M19**, tùy hành vi                             | Chuỗi trạng thái cuốc, GPS, thời gian chờ, khoản thu, chứng từ và phản ánh             | Các nguồn đã kiểm tra chưa đủ để khẳng định một mô hình riêng bao phủ tốt mọi thủ đoạn trong nhóm này.                |

**Với dự án của bạn, các nguồn đáng đọc trước là Trust Counter, phương pháp logistic phát hiện đường vòng, RGCN, GraphBEAN và A* bot.** Chúng lần lượt giúp thiết kế kiểm tra hành vi lặp lại, phân tích hành trình, tìm nhóm thông đồng, gán nhãn bất thường và hỗ trợ chuyên viên tổng hợp bằng chứng.

Một điểm thiết kế có cơ sở triển khai rõ là **tách điểm bất thường khỏi kết luận gian lận**: Uber Risk Entity Watch đưa cảnh báo kèm giải thích cho chuyên viên xem xét; Grab GraphBEAN kết hợp điểm bất thường, nhãn hành vi và tín hiệu bổ sung trước khi xử lý. Đây là hai mẫu phù hợp để tham khảo cho luồng ticket và reviewer của hệ thống. [Uber Risk Entity Watch](https://www.uber.com/us/en/blog/risk-entity-watch/), [Grab GraphBEAN](https://engineering.grab.com/graph-anomaly-model).
